brew "bat"
brew "cargo-binstall"
brew "docker"
brew "docker-compose"
brew "docker-credential-helper"
brew "fzf"
brew "gh"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "mise"
brew "p7zip"
brew "pipx"
brew "podman"
brew "podman-compose"
brew "sheldon"
brew "yq"
brew "zellij"
brew "hashicorp/tap/terraform"
cask "ghostty"
cask "gcloud-cli"
cask "visual-studio-code"
mas "Magnet", id: 441258766
mas "Snippety", id: 1530751461
mas "TextSniper", id: 1528890965
