import = [
    # "~/.config/alacritty/themes/alacritty_0_12.toml",
    # "~/.config/alacritty/themes/brogrammer.toml",
    # "~/.config/alacritty/themes/solarized_dark_higher_contrast.toml",
    "~/.config/alacritty/themes/github_dark_default.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
style = "Regular"

[window]
blur = true
startup_mode = "Windowed"
dynamic_title = true
# opacity = 0.8
option_as_alt = "Both"

[window.dimensions]
columns = 160
lines = 50

[window.padding]
x = 4
y = 4
