#!/bin/sh

exec < /dev/tty
cat << EOF
Author: $(git config --get user.name) <$(git config --get user.email)>
Date:   $(date -R)

    $(cat $1)

EOF
while true; do
    read -p "Do you want to finalize this change (y/n)? " yn
    case $yn in
        [Yy]* ) exit 0;;
        [Nn]* ) exit 1;;
        * ) echo "Please answer 'y' or 'n'";;
    esac
done
