#!/bin/sh

if [ -x .git/hooks/$(basename $0) ]; then
  .git/hooks/$(basename $0) "$@" || exit $?
fi

set -e

if command -v shellcheck > /dev/null 2>&1; then
    $(dirname $0)/scripts/shellcheck.py
else
    echo 'Warning: "shellcheck" is not installed, skipping the pre-commit hook.' >&2
fi
if command -v gitleaks > /dev/null 2>&1; then
    $(dirname $0)/scripts/gitleaks.py
else
    echo 'Warning: "gitleaks" is not installed, skipping the pre-commit hook.' >&2
fi
printf '\n'
