[settings.pipx]
uvx = true

[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
cargo-binstall = "latest"
"cargo:bat" = "latest"
"cargo:sheldon" = "latest"
"cargo:zellij" = "latest"
fzf = "latest"
gcloud = "latest"
gh = "latest"
gitleaks = "latest"
jq = "latest"
kubectl = "latest"
node = "lts"
"pipx:Faker" = "latest"
"pipx:checkov" = "latest"
"pipx:coolname" = "latest"
"pipx:jc" = "latest"
"pipx:podman-compose" = "latest"
"pipx:tox" = "latest"
python = "latest"
terraform = "latest"
uv = "latest"
yq = "latest"
